url:
  rest: https://api.upbit.com
  ws: wss://api.upbit.com/websocket/v1
candle:
  units: [1, 10, 60]
  count: 200
rate_limit:
  api_calls_per_second: 5
partition:
  retain_days: 30
  retain_months: 6
  create: 3
